### ISSUE TITLE
Queue is clogged

### ISSUE THREAD

**Issue by AtilioA** [bennofs/wdumper#28]
Right now, there are [58 workers, and queue length is reaching 100 entries](https://wdumps.toolforge.org/status). Many entries have been processing for well over a month, and newer requests have to wait for that or even more to get a chance to be processed.

This is rendering the service unusable; perhaps a processing time limit should be put in place, and/or free the queue altogether? I guess most people that requested a dump one month ago have moved on already...

**Comment by Moradnejad** [comment]
Can someone check on this issue.

**Comment by lydiapintscher** [comment]
@addshore and I were also just running into this. Is there anything that can be done? Anything we can help with?

**Comment by fsalerno-sdc** [comment]
I agree, I think old dump requests should be pruned. Perhaps there should also be a filter to prevent requesting dumps that are too broad or complex.

**Comment by bennofs** [comment]
Thanks for your interest in the tool, and sorry for staying dormant so long. I'll take a look sometime this week.

**Comment by AtilioA** [comment]
A reasonable solution would be to create a timeout. If a queue entry is taking longer than x (let's say, 60 days), it is stopped.
A complexity analysis of the query might require too much work initially, so that could be looked into later.

**Comment by bennofs** [comment]
i think it is not a resource problem, but rather a reliability problem. The number of workers on the status page isn't correct, right now there is always only a single worker.

What happened this time is that the worker process terminated *partially* with an `input/output` error. Due to the partial termination, the automatic restart mechanism didn't catch it (since the process was still alive, only one of its threads died). For now, I restarted the worker. I'll also restart the old dumps and watch the process more closely, to see if the issue reappears.

In general, the communication/interface to the worker needs to be improved so that there is some kind of periodic healthcheck or something so that errors can be dealt. Also the reliability of the worker needs to be improved, it shouldn't happen that the process continues to live on in a half-dead state. I'll look at that next week.

**Comment by bennofs** [comment]
I found the issue: when the main thread runs into an exception, it prins the stacktrace and returns. However, there are still non-daemon threads running, which means that the process as a whole will not exit.

This issue should be fixed by https://github.com/bennofs/wdumper/commit/99f39d1c2142aaf6ffe1f242bebe2e7a895bf174, which I just deployed to toolforge.
